// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsuWjVoNzUJfnrHezN_ATsqT4erFxTrLw',
    appId: '1:373158700266:web:placeholder',
    messagingSenderId: '373158700266',
    projectId: 'caratone-1098a',
    authDomain: 'caratone-1098a.firebaseapp.com',
    databaseURL: 'https://caratone-1098a-default-rtdb.firebaseio.com',
    storageBucket: 'caratone-1098a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuWjVoNzUJfnrHezN_ATsqT4erFxTrLw',
    appId: '1:373158700266:android:3aa16ddba9a4d447572393',
    messagingSenderId: '373158700266',
    projectId: 'caratone-1098a',
    databaseURL: 'https://caratone-1098a-default-rtdb.firebaseio.com',
    storageBucket: 'caratone-1098a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcOKkQCVJAEbHmC6FYSwx5vYeVnVxjsc',
    appId: '1:373158700266:ios:57f87ec38a55f7ad572393',
    messagingSenderId: '373158700266',
    projectId: 'caratone-1098a',
    databaseURL: 'https://caratone-1098a-default-rtdb.firebaseio.com',
    storageBucket: 'caratone-1098a.firebasestorage.app',
    iosBundleId: 'com.invoice.generator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcOKkQCVJAEbHmC6FYSwx5vYeVnVxjsc',
    appId: '1:373158700266:ios:57f87ec38a55f7ad572393',
    messagingSenderId: '373158700266',
    projectId: 'caratone-1098a',
    databaseURL: 'https://caratone-1098a-default-rtdb.firebaseio.com',
    storageBucket: 'caratone-1098a.firebasestorage.app',
    iosBundleId: 'com.invoice.generator',
  );
}
