// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBbce9ZWxmPkFNiQ5YS8x4XW9OQyDfh0As",
  authDomain: "caratone-1098a.firebaseapp.com",
  databaseURL: "https://caratone-1098a-default-rtdb.firebaseio.com",
  projectId: "caratone-1098a",
  storageBucket: "caratone-1098a.firebasestorage.app",
  messagingSenderId: "373158700266",
  appId: "1:373158700266:web:86016408e4df8718572393",
  measurementId: "G-4F11D0RVGT"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuWjVoNzUJfnrHezN_ATsqT4erFxTrLw',
    appId: '1:373158700266:android:f2f9e30bf194fae5572393',
    messagingSenderId: '373158700266',
    projectId: 'caratone-1098a',
    databaseURL: 'https://caratone-1098a-default-rtdb.firebaseio.com',
    storageBucket: 'caratone-1098a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcOKkQCVJAEbHmC6FYSwx5vYeVnVxjsc',
    appId: '1:373158700266:ios:484aed7b2d53e3bf572393',
    messagingSenderId: '373158700266',
    projectId: 'caratone-1098a',
    databaseURL: 'https://caratone-1098a-default-rtdb.firebaseio.com',
    storageBucket: 'caratone-1098a.firebasestorage.app',
    iosBundleId: 'com.mobile.caratone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcOKkQCVJAEbHmC6FYSwx5vYeVnVxjsc',
    appId: '1:373158700266:ios:57f87ec38a55f7ad572393',
    messagingSenderId: '373158700266',
    projectId: 'caratone-1098a',
    databaseURL: 'https://caratone-1098a-default-rtdb.firebaseio.com',
    storageBucket: 'caratone-1098a.firebasestorage.app',
    iosBundleId: 'com.mobile.caratone',
  );
}
